### PR TITLE
docs(tools): added fastify-helmet to hardening

### PR DESCRIPTION
**Pull request by alemagio**
Just saw fastify was missing on the list.

### CODE REVIEW

**Comment by lirantal** [comment]
Thanks!

**Comment by alemagio** [comment]
Can I merge it myself? :scream:

**Comment by lirantal** [comment]
Exactly! 😉

**Comment by alemagio** [comment]
> Oh, not at all. I was under the impression only the hacktoberfest label is required.
I'm afraid it is not :disappointed: .

> Ping me your other PRs and let's make sure we assign them them all
No problem, opening another one soon :wink:

**Pull request merged**
