### PR TITLE
Add joi-security CLI to vulnerabilities list

### PR DESCRIPTION
**Pull request by Saluki**
Hi,

I would like to contribute to this list by adding a new CLI tool named [joi-security](https://github.com/Saluki/joi-security). The goal of this tool is to analyze Joi validation schemas and detect potential security flaws such as XSS attacks, SQL injections or path traversal attempts (allowing developers to strenghten their validation schemas).

Thanks!

### CODE REVIEW

**Comment by alemagio** [comment]
Hi, thanks for adding it!
Would you mind make your commit to follow [angular-commit-guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit)?
Something like `docs(advisories): ...`.

**Comment by lirantal** [comment]
@alemagio once you click on squash and merge you can update the actual commit message instead of the one used in the PR. Want to test if it works for you?

**Comment by alemagio** [comment]
> @alemagio once you click on squash and merge you can update the actual commit message instead of the one used in the PR. Want to test if it works for you?
I'm such a noob :joy: 

Sure I'll do it

**Comment by lirantal** [comment]
Hurray! 👏

**Comment by Saluki** [comment]
Thanks @alemagio !
My bad, I forgot the Angular commit guidelines...

**Comment by alemagio** [comment]
@Saluki 
We both learnt something :smile:

**Pull request merged**
