### PR TITLE
Added DevSkim

### PR DESCRIPTION
**Pull request by omerlh**
@lirantal WDYT about Dynamic Analysis? Worth adding a section? I can add Zaproxy to there, maybe also worth adding burp.

### CODE REVIEW

**Comment by lirantal** [comment]
Is DevSkim compatible with Node.js / JavaScript? Since that repo could use some documentation love maybe you can also link in the articles section to a post about it? (or write one? :-) )

About the dynamic options - because there is nothing Node.js specific about them I feel reluctant about adding them, but if you can link to articles that cover using them and specifically target Node.js IMO that would be better.

Open for comments if anyone else want to express their ideas as well.

**Comment by omerlh** [comment]
According to this [doc](https://github.com/Microsoft/DevSkim/wiki/applies_to) DevSkim is compatible with JS. I added it because it is a really good static analysis tool - the IDE integration is amazing. I have not tested it on JS behind what claims by the official docs.
Good point about dynamic analysis.

**Comment by lirantal** [comment]
Cool let's add it!
I'd be happy to give it a test run

**Comment by omerlh** [comment]
Please share how it goes! My test drive with C# was so fun, I hope they have similar experience for JS...

**Pull request merged**
